version: 2
jobs:
  build:
    docker:
    # TODO: change this to sagemath/sagemath:develop once all dependencies of 22956 have been merged.
    - image: saraedum/sagemath:henselization
      entrypoint: bash
    steps:
    - type: checkout
      path: /home/sage/sage/henselization
    - type: run
      working_directory: /home/sage/sage
      command: |
        chmod go-w .
        ./sage -tp --long --initial henselization
