version: 2
jobs:
  build:
    docker:
    - image: saraedum/sagemath:develop
      entrypoint: bash
    steps:
    - type: checkout
      path: /home/sage/sage/completion
    - type: run
      working_directory: /home/sage/sage
      command: |
        export SAGE_NUM_THREADS=4
        chmod go-w .
        ./sage -tp completion
