version: 2
jobs:
  build:
    docker:
    - image: saraedum/sagemath:develop
      entrypoint: bash
    steps:
    - type: checkout
      path: /home/sage/sage/henselization
    - type: run
      working_directory: /home/sage/sage
      command: |
        chmod go-w .
        ./sage -tp --long --initial henselization
